# Generated by Django 3.1.5 on 2021-02-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('vtype', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('image', 'Image'), ('url', 'URL')], max_length=10)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Notem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('image', 'Image'), ('url', 'URL')], max_length=10)),
                ('ndata', models.CharField(max_length=256)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.notem')),
            ],
        ),
    ]
