# Generated by Django 3.1.5 on 2021-05-01 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Note',
                'verbose_name_plural': 'Topic Notes',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=600)),
                ('imagename', models.CharField(max_length=60)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='UserNotem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currdeck', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('notem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.notem')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srmethod', models.CharField(choices=[('LBOXP', 'Leitnes Box - Progressive'), ('LBOXR', 'Leitnes Box - Restart')], max_length=10)),
                ('maxdeck', models.PositiveSmallIntegerField(default=3)),
                ('dclimit', models.PositiveSmallIntegerField(default=10)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Topic',
                'verbose_name_plural': 'User Topics',
            },
        ),
        migrations.CreateModel(
            name='UserNotemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currdeck', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('ueval', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('nextdeck', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('usernotem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.usernotem')),
            ],
        ),
        migrations.AddField(
            model_name='usernotem',
            name='usertopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.usertopic'),
        ),
        migrations.CreateModel(
            name='UserLearningDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usernotem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.usernotem')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('vtype', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('image', 'Image'), ('url', 'URL'), ('html', 'HTML'), ('example', 'Example')], max_length=10)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(help_text='User log inforation ...', max_length=300)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usernotem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.usernotem')),
            ],
        ),
        migrations.AddField(
            model_name='notem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.topic'),
        ),
        migrations.CreateModel(
            name='Noted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('image', 'Image'), ('url', 'URL'), ('html', 'HTML'), ('example', 'Example')], max_length=10)),
                ('ndata', models.CharField(max_length=612)),
                ('audio', models.CharField(blank=True, max_length=60, null=True)),
                ('norder', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.notem')),
            ],
            options={
                'verbose_name': 'Topic Note Detail',
                'verbose_name_plural': 'Topic Note Details',
            },
        ),
    ]
