# Generated by Django 3.1.5 on 2021-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0002_notem_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noted',
            name='ndata',
            field=models.CharField(max_length=612),
        ),
    ]
