# Generated by Django 3.1.5 on 2021-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0003_auto_20210219_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='noted',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
