# Generated by Django 3.1.5 on 2021-02-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0004_noted_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noted',
            old_name='name',
            new_name='notem',
        ),
    ]
