# Generated by Django 3.1.5 on 2021-02-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0005_auto_20210220_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noted',
            old_name='order',
            new_name='norder',
        ),
    ]
