# Generated by Django 3.1.5 on 2021-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0006_auto_20210220_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noted',
            name='ntype',
            field=models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('image', 'Image'), ('url', 'URL'), ('example', 'Example')], max_length=10),
        ),
        migrations.AlterField(
            model_name='template',
            name='vtype',
            field=models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('image', 'Image'), ('url', 'URL'), ('example', 'Example')], max_length=10),
        ),
    ]
