# Generated by Django 3.1.5 on 2021-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0007_auto_20210220_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='noted',
            name='audio',
            field=models.CharField(default='x', max_length=60),
            preserve_default=False,
        ),
    ]
