# Generated by Django 3.1.5 on 2021-02-21 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ucm', '0008_noted_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currdeck', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('notem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.notem')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currdeck', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('ueval', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('nextdeck', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('usernotem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.usernotem')),
            ],
        ),
        migrations.AddField(
            model_name='usernotem',
            name='usertopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.usertopic'),
        ),
    ]
