# Generated by Django 3.1.5 on 2021-02-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0009_auto_20210221_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='Not available', max_length=600),
            preserve_default=False,
        ),
    ]
