# Generated by Django 3.1.5 on 2021-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0010_auto_20210224_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='imagename',
            field=models.CharField(default='NA', max_length=60),
            preserve_default=False,
        ),
    ]
