# Generated by Django 3.1.5 on 2021-02-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0011_topic_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
