# Generated by Django 3.1.5 on 2021-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0012_topic_mdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='srmethod',
            field=models.CharField(choices=[('LBOXP', 'Leitnes Box - Progressive'), ('LBOXR', 'Leitnes Box - Restart')], default='LBOXP', max_length=10),
            preserve_default=False,
        ),
    ]
