# Generated by Django 3.1.5 on 2021-02-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0013_usertopic_srmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('currdeck', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('notem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.notem')),
                ('usertopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucm.usertopic')),
            ],
        ),
    ]
