# Generated by Django 3.1.5 on 2021-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0015_auto_20210226_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='maxdeck',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
