# Generated by Django 3.1.5 on 2021-03-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0016_usertopic_maxdeck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noted',
            options={'verbose_name': 'Topic Note Detail', 'verbose_name_plural': 'Topic Note Details'},
        ),
        migrations.AlterModelOptions(
            name='notem',
            options={'verbose_name': 'Topic Note', 'verbose_name_plural': 'Topic Notes'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='usertopic',
            options={'verbose_name': 'User Topic', 'verbose_name_plural': 'User Topics'},
        ),
        migrations.AlterField(
            model_name='noted',
            name='audio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
