# Generated by Django 3.1.5 on 2021-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0017_auto_20210301_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='dclimit',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
