# Generated by Django 3.1.5 on 2021-03-03 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ucm', '0019_userlearningdeck_cuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotem',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotem',
            name='mdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
